# Generated by Django 4.2.1 on 2023-07-03 00:14

import Inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.IntegerField(unique=True, validators=[Inventario.models.validate_unique_name]),
        ),
    ]
