# Generated by Django 4.2.2 on 2023-07-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_productos_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='iva',
            field=models.BooleanField(default=True),
        ),
    ]
