# Generated by Django 4.2.2 on 2023-07-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_productos_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='iva',
            field=models.IntegerField(),
        ),
    ]
