# Generated by Django 4.2.2 on 2023-07-22 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTipoDeCambio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cambio', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='IdentificadorProductos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialProductos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iva', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.identificadorproductos')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('total_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cancelado_en_divisa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impuesto_divisa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cancelado_en_bs', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.clientes')),
                ('id_tipo_de_cambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.historialtipodecambio')),
                ('productos', models.ManyToManyField(to='Ventas.historialproductos')),
            ],
        ),
    ]
