# Generated by Django 4.2.2 on 2023-07-12 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField()),
                ('nombreCompelto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('total', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='IdentificadorProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iva', models.BooleanField()),
                ('precio', models.IntegerField()),
                ('factura', models.ManyToManyField(to='Ventas.facturas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.identificadorproducto')),
            ],
        ),
    ]
