# Generated by Django 4.2.2 on 2023-07-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
        migrations.RenameModel(
            old_name='IdentificadorProducto',
            new_name='IdentificadorProductos',
        ),
    ]
