# Generated by Django 4.2.2 on 2023-07-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialproductos',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
