# Generated by Django 4.2.2 on 2023-07-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_historialproductos_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialproductos',
            name='total_producto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
