# Generated by Django 4.2.2 on 2023-07-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_rename_cliente_clientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='total',
        ),
        migrations.AddField(
            model_name='facturas',
            name='abono_divisa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facturas',
            name='impuesto_divisa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facturas',
            name='iva_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facturas',
            name='total_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facturas',
            name='total_cancelado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historialproductos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
