# Generated by Django 4.2.2 on 2023-07-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_remove_historialproductos_total_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
