# Generated by Django 4.2.2 on 2023-07-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_historialtipodecambio_remove_clientes_nombrecompelto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtipodecambio',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
