# Generated by Django 4.2.2 on 2023-07-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_facturas_vuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
