# Generated by Django 4.2.2 on 2023-07-20 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_alter_historialtipodecambio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtipodecambio',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
