# Generated by Django 4.2.2 on 2023-07-20 02:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0006_alter_historialtipodecambio_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='cliente',
        ),
        migrations.AddField(
            model_name='facturas',
            name='id_cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Ventas.clientes'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='id_tipo_de_cambio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Ventas.historialtipodecambio'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
