# Generated by Django 4.2.2 on 2023-07-20 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0007_remove_facturas_cliente_facturas_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.clientes'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='id_tipo_de_cambio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.historialtipodecambio'),
        ),
    ]
