# Generated by Django 4.2.2 on 2023-07-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0008_alter_facturas_id_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturas',
            old_name='total_cancelado',
            new_name='total_cancelado_en_bs',
        ),
        migrations.AlterField(
            model_name='historialproductos',
            name='iva',
            field=models.IntegerField(),
        ),
    ]
