# Generated by Django 4.2.2 on 2023-07-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0010_alter_historialtipodecambio_cambio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturas',
            old_name='total_cancelado_en_bs',
            new_name='cancelado_en_bs',
        ),
        migrations.RenameField(
            model_name='facturas',
            old_name='abono_divisa',
            new_name='cancelado_en_divisa',
        ),
        migrations.RenameField(
            model_name='facturas',
            old_name='iva_total',
            new_name='iva',
        ),
        migrations.AddField(
            model_name='facturas',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
