# Generated by Django 4.2.2 on 2023-07-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0011_rename_total_cancelado_en_bs_facturas_cancelado_en_bs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialproductos',
            name='factura',
        ),
        migrations.AddField(
            model_name='facturas',
            name='productos',
            field=models.ManyToManyField(to='Ventas.historialproductos'),
        ),
    ]
