# Generated by Django 4.2.2 on 2023-07-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
            ],
        ),
    ]
